spring:
  application:
    #设置当前项目的名称，这个名字会提交给Nacos做当前微服务项目的名称
    name: nacos-business
  cloud:
    nacos:
      discovery:
        #配置Nacos的位置 用于提交当前的信息
        server-addr: localhost:8848
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
seata:
  tx-service-group: csmall_group
  service:
    vgroup-mapping:
      csmall_group: default
    grouplist:
      default: localhost:8091